'use client'

import '@/app/globals.css'
import { useEffect } from 'react'

// export const metadata = {
// 	title: 'Next.js',
// 	description: 'Generated by Next.js',
// }

const RootLayout = ({ children }) => {
	useEffect(() => {
		const setViewportHeight = () => {
			document.documentElement.style.setProperty(
				'--vh',
				`${window.innerHeight * 0.01}px`,
			)
		}

		// Set height on load and on resize
		setViewportHeight()
		window.addEventListener('resize', setViewportHeight)

		// Cleanup event listener
		return () => {
			window.removeEventListener('resize', setViewportHeight)
		}
	}, [])

	return (
		<html lang='en'>
			<body
				className='flex flex-col'
				style={{ height: 'calc(var(--vh, 1vh) * 100)' }}
			>
				<header className='bg-gray-100 text-black py-4'>
					<h1 className='text-center text-lg'>Empress Origin</h1>
				</header>

				<main className='bg-gray-200 text-red-300 flex-grow'>{children}</main>

				<footer className='bg-gray-100 text-black py-4'>
					<p className='text-center text-sm text-black'>
						© 2024 Empress Origin. All Rights Reserved.
					</p>
				</footer>
			</body>
		</html>
	)
}

export default RootLayout
